###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nomb_cliente":"Raul Fernandez",
    "telefono":78925661820,
    "ciudad":"DF",
    "calle":"San Juan",
    "numero":1770,
    "estado":"DF",
    "fecha_nacimiento":"28/10/1985"
}

###

GET http://localhost:9000/api/users HTTP/1.1


###
GET http://localhost:9000/api/users/639bc25a8f79a92a9313b93c HTTP/1.1


###
PUT http://localhost:9000/api/users/639bc25a8f79a92a9313b93c HTTP/1.1
Content-Type: application/json

{
  "nomb_cliente": "Juliana Torres",
  "telefono": 8892651780,
  "ciudad": "Guadalajara",
  "calle": "Girasoles",
  "numero": 1180,
  "estado": "Jalisco",
  "fecha_nacimiento": "27/12/2000"
}


###
DELETE http://localhost:9000/api/users/639cddd91a1cdb580620ef18 HTTP/1.1