###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre":"Karla torres",
    "correo":"karla@gmail.com",
    "username":"karlato",
    "contraseña":"123456789"
}

###

GET http://localhost:9000/api/users HTTP/1.1


###
GET http://localhost:9000/api/users/639bc25a8f79a92a9313b93c HTTP/1.1


###
PUT http://localhost:9000/api/users/63a0f0dcc64c73bb88dacd8a HTTP/1.1
Content-Type: application/json

{
    "nombre":"Karla torres",
    "correo":"karla@gmail.com",
    "username":"karlatorres",
    "contraseña":"123456789"
}


###
DELETE http://localhost:9000/api/users/639bc01f649b9bb8a9d4e1ae HTTP/1.1